name: CI
on:
  push:
    paths-ignore:
      - "demo/**"
      - "docs/**"
      - "**.md"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Yarn Install
        run: yarn install
      - name: StyleLint
        run: ./scripts/stylelint.sh
      - name: ESLint
        run: yarn run eslint app/**/*.js
